### ISSUE TITLE
quippy calculate forces creates an Atoms.arrays["force"] which has wrong shape

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#144]
Calling get_forces from ASE on an object with a quippy Potential as a calculator creates a "force" entry in Atoms.arrays, which has the wrong (transpose) shape.  Demo script attached 

[quippy_force_shape_bug.py.gz](https://github.com/libAtoms/QUIP/files/3530778/quippy_force_shape_bug.py.gz)

My output is

```tin 1260 : ./quippy_force_shape_bug.py 
2
Lattice="10.0 0.0 0.0 0.0 10.0 0.0 0.0 0.0 10.0" Properties=species:S:1:pos:R:3 pbc="F F F"
Si       0.00000000       0.00000000       0.00000000 
Si       2.50000000       0.00000000       0.00000000 
Calling QUIP Potential.calc() with args_str "  energy force"
WARNING: Potential_calc: cutoff of Atoms object (-1.0000000000000000) < Potential cutoff (3.9258000000000002) - increasing it now
calc energy -2.066647404669778
col shape numbers (2,)
col shape positions (2, 3)
col shape forces (2, 3)
col shape force (3, 2)
/share/apps/ase/ase-local/2019-08-20/lib/python3.6/site-packages/ase-3.19.0b1-py3.6.egg/ase/io/extxyz.py:844: UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator
  'from calculator'.format(key))
Traceback (most recent call last):
  File "./quippy_force_shape_bug.py", line 61, in <module>
    ase.io.write(sys.stdout, at, format="xyz")
  File "/share/apps/ase/ase-local/2019-08-20/lib/python3.6/site-packages/ase-3.19.0b1-py3.6.egg/ase/io/formats.py", line 406, in write
    **kwargs)
  File "/share/apps/ase/ase-local/2019-08-20/lib/python3.6/site-packages/ase-3.19.0b1-py3.6.egg/ase/io/formats.py", line 439, in _write
    io.write(fd, images, **kwargs)
  File "/share/apps/ase/ase-local/2019-08-20/lib/python3.6/site-packages/ase-3.19.0b1-py3.6.egg/ase/io/extxyz.py", line 866, in write_xyz
    data[column + str(c)] = value[:, c]
ValueError: could not broadcast input array from shape (3) into shape (2)
```

**Comment by jameskermode** [comment]
Should now be fixed, please re-open if not!
