### ISSUE TITLE
set_cutoff_factor() missing

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#18]
I have some configurations that have picked up a 'cutoff_factor' that are causing issues when converting into quippy Atoms:

```
>>> from ase.lattice.bulk import bulk
>>> from quippy import Atoms
>>> b = bulk('Fe')
>>> b.info['cutoff_factor'] = 1.2
>>> a = Atoms(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tdd20/.local/lib64/python2.7/site-packages/quippy/atoms.py", line 406, in __init__
    self.copy_from(symbols)
  File "/home/tdd20/.local/lib64/python2.7/site-packages/quippy/atoms.py", line 734, in copy_from
    self.set_cutoff_factor(other.info['cutoff_factor'],
  File "/home/tdd20/.local/lib64/python2.7/site-packages/quippy/atoms.py", line 779, in __getattr__
    raise AttributeError('Unknown Atoms attribute %s' % name)
AttributeError: Unknown Atoms attribute set_cutoff_factor
```

The call is in:

```
quippy/quippy/atoms.py
733:                if 'cutoff_factor' in other.info:
734:                    self.set_cutoff_factor(other.info['cutoff_factor'],
735:                                           other.info.get('cutoff_factor_break'))
```

There are a few other spots still trying to call that method (I was confused because there is one in test that wasn't failing but that test it disabled):

```
% ag set_cutoff_factor
src/Potentials/IPModel_BOP.f95
766:!!$       call set_cutoff_factor(aa, a%cutoff)

tests/test_electrostatic_embed.py
123:       cluster2.set_cutoff_factor(1.2)
145:       cluster.set_cutoff_factor(1.2)

quippy/examples/quartz-strain.py
131:   aqc.set_cutoff_factor(1.2)

quippy/quippy/crack.py
760:    tmp_atoms.set_cutoff_factor(nneightol)

quippy/quippy/plot3d.py
56:    at.set_cutoff_factor(cutoff_factor)

quippy/quippy/cp2k.py
410:    at_avg.set_cutoff_factor(1.2)

quippy/quippy/atoms.py
734:                    self.set_cutoff_factor(other.info['cutoff_factor'],
```

Can these just be removed?

**Comment by jameskermode** [comment]
Well spotted! Yes, all of these should simply be removed- please go ahead and do this if you have time.

These cutoff changes have haunted us for longer than I thought possible!
