### ISSUE TITLE
Error in importing quippy.potential

### ISSUE THREAD

**Issue by prasantapaul93** [libAtoms/QUIP#222]
I want to import quippy.potential but I got this error 
>>> from quippy.potential import Potential
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'quippy.potential'
Can you please help me out? is it an installation problem?

**Comment by gabor1** [comment]
did you install quippy? what happens if you type "import quippy" ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by prasantapaul93** [comment]
import quippy is working fine

**Comment by prasantapaul93** [comment]
The same error is also coming for descriptor. 
from quippy.descriptors import Descriptor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'quippy.descriptors'

**Comment by gabor1** [comment]
What happens if you type

import quippy
quippy.__file__

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by prasantapaul93** [comment]
It worked fine.

**Comment by prasantapaul93** [comment]
![quippy](https://user-images.githubusercontent.com/68603577/88073347-b4130d80-cb93-11ea-891b-1025b835fc68.png)
This is a screenshot of my current screen

**Comment by gabor1** [comment]
it’s supposed to print the name of the module file!!



maybe type print(quippy.__file__)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Jul 21, 2020, at 11:25 AM, gabor1 <notifications@github.com> wrote:
> it’s supposed to print the name of the module file!!
> 
> maybe type print(quippy.__file__)

I suspect that the quippy installation is broken.

**Comment by gabor1** [comment]
maybe best start with a clean quip/quippy clone and install! (maybe even a clean python environment…)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by jameskermode** [comment]
Are you importing quippy from the source directly, by any chance? Please chance to another directory first.

**Comment by prasantapaul93** [comment]
![quippy_2](https://user-images.githubusercontent.com/68603577/88075883-01dd4500-cb97-11ea-8129-ebe5b017d955.png)
This is the output of print(quippy.__file__)

**Comment by bernstei** [comment]
> On Jul 21, 2020, at 11:43 AM, prasantapaul93 <notifications@github.com> wrote:
> 
> This is the output of print(quippy.file)

That's a sign of running python when sitting directly above the "quippy/" source directory, rather than having the quippy installation directory be in PYTHONPATH, or being in the right place under the 'build/" subdirectory.

**Comment by gabor1** [comment]
well, something really went wrong with the quippy installation. try to do it from fresh, following the instructions carefully (and keep the log file of the compilation and installation, so that we can inspect it afterwards!)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
but do check your current directory first, obviously...

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by prasantapaul93** [comment]
> On Jul 21, 2020, at 11:43 AM, prasantapaul93 ***@***.***> wrote: This is the output of print(quippy.file)
> That's a sign of running python when sitting directly above the "quippy/" source directory, rather than having the quippy installation directory be in PYTHONPATH, or being in the right place under the 'build/" subdirectory.

I checked it again and I am not in the source directory. I have updated pythonpath also but it didn't
 work

**Comment by prasantapaul93** [comment]
> well, something really went wrong with the quippy installation. try to do it from fresh, following the instructions carefully (and keep the log file of the compilation and installation, so that we can inspect it afterwards!)
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 21 Jul 2020, at 16:43, prasantapaul93 ***@***.***> wrote: This is the output of print(quippy.file) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

ok. I will install it again

**Comment by gabor1** [comment]
So now go do a fresh clone/compile/install, but keep all the printed output so we can inspect it and help you

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
The only way I know of to get module.__file__ to be None is if you have a directory called "module" either in the current directory, or someplace in your PYTHONPATH, but that directory is empty instead of having a proper installation of the relevant python module.  Most likely something went wrong with your quippy installation, and it created the quippy directory but did not populate it.  If you follow Gábor's suggestions and keep all the output, you nay be able to figure out where it installed quippy and what went wrong.

									Noam

**Comment by gabor1** [comment]
any luck?
