### ISSUE TITLE
quippy Descriptor interfaces behaves badly for SOAP with center Z specified but no such atoms included

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#223]
configuration-average descriptor returns NaN, and per-atom descriptor gives a python error.

```> cat t.py 
import numpy as np
from quippy.descriptors import Descriptor
from ase.atoms import Atoms

at = Atoms('Si5', scaled_positions=np.random.uniform(size=(5,3)), cell=(4,4,4))

print('average descriptor')
d = Descriptor('soap n_max=3 l_max=3 cutoff=4.0 atom_sigma=0.5 Z=6 average')
v = d.calc(at)
print(v)

print('')

print('per-atom descriptor')
d = Descriptor('soap n_max=3 l_max=3 cutoff=4.0 atom_sigma=0.5 Z=6')
v = d.calc(at)
print(v)


> python t.py 
average descriptor
{'covariance_cutoff': array([1.]), 'data': array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.]]), 'has_data': array([1]), 'ci': array([], dtype=int32)}

per-atom descriptor
Traceback (most recent call last):
  File "t.py", line 16, in <module>
    v = d.calc(at)
  File "/share/apps/quip/quip-local/mkl/2020-04-15/serial/lib64/python3.6/site-packages/quippy-_home_cluster2_bernstei_src_work_git_canonical_copies_QUIP.git_286bc70_dirty-py3.6-linux-x86_64.egg/quippy/descriptors.py", line 44, in wrapper
    return method(self, _quip_at, *args, **kw)
  File "/share/apps/quip/quip-local/mkl/2020-04-15/serial/lib64/python3.6/site-packages/quippy-_home_cluster2_bernstei_src_work_git_canonical_copies_QUIP.git_286bc70_dirty-py3.6-linux-x86_64.egg/quippy/descriptors.py", line 204, in calc
    descriptor_out['data'] = descriptor_out['data'].reshape((count, -1))
KeyError: 'data'
```

**Comment by albapa** [comment]
These two problems are separate. Problem #1 is internal to GAP and I suspect it is due to a division by zero at the normalisation step. Problem #2 is a quippy problem - for some reason it cannot deal with zero descriptors returned.

**Comment by albapa** [comment]
Commit e129630 should fix the first problem.

**Comment by albapa** [comment]
Commit 1ff93b3 should fix the second problem.

**Comment by bernstei** [comment]
Thanks.  I'll update my quippy and GAP and see if it's working.
