### ISSUE TITLE
errors in GAP potential fitting

### ISSUE THREAD

**Issue by GengSS** [libAtoms/QUIP#229]
Dear libAtoms and QUIP developers and users,

I just started to learn to use the gap_fit program to reproduce the tutorial results on 
https://libatoms.github.io/GAP/gap_fitting_tutorial.html,

Here is the command line string
`/u/project/sautet/gengsun/programs/QUIP/QUIP/build/linux_x86_64_gfortran/gap_fit energy_parameter_name=energy force_parameter_name=forces do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}`

and below are are few lines about the train.xyz,

```
81
Lattice="9.312844978309194 0.0 0.0 0.0 9.312844978309194 0.0 0.0 0.0 9.312844978309194" Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy=71.71319028943991 pbc="T T T"
O        0.00000000       0.00000000       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       0.76323900       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       8.54960598       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       0.00000000       3.22354366      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       0.76323900       2.62723466       0.00000000       5.21893682      -4.05591796       1.35042099
```

Unfortunately, I encountered an error as below:

```
SYSTEM ABORT: Traceback (most recent call last)
File "/u/home/g/gengsun/project/programs/QUIP/QUIP/src/libAtoms/linearalgebra.f95", line 2329 kind
unspecified
LA_Matrix_Factorise: cannot factorise, error: 9
```

It is not clear to me what is the source for the error, and I greatly appreciate any suggestions.

Thank you very much in advance.

Best,

Geng

**Comment by gabor1** [comment]
Can you please paste the entire output

-- Gábor

**Comment by gabor1** [comment]
Also please drop in  the first frame of your training XYZ file, I'd like to run the training command myself.

-- Gábor

**Comment by GengSS** [comment]
Thanks for your quick reply.

Here is the full output:

```
libAtoms::Hello World: 15/08/2020   18:38:42
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,1ff93b3-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Aug 15 2020 at 15:17:21
libAtoms::Hello World: Random Seed = 67122154
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default


================================ Input parameters ==============================

atoms_filename = //MANDATORY//
at_file = train.xyz
gap = "distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10"
e0 = 0.0
local_property0 = 0.0
e0_offset = 0.0
e0_method = isolated
default_kernel_regularisation = //MANDATORY//
default_sigma = "0.008 0.04 0 0"
sparse_jitter = 1.0e-10
hessian_displacement = 1.0e-2
hessian_delta = 1.0e-2
baseline_param_filename = quip_params.xml
core_param_file = quip_params.xml
baseline_ip_args =
core_ip_args =
energy_parameter_name = energy
local_property_parameter_name = local_property
force_parameter_name = forces
virial_parameter_name = virial
hessian_parameter_name = hessian
config_type_parameter_name = config_type
kernel_regularisation_parameter_name = sigma
sigma_parameter_name = sigma
force_mask_parameter_name = force_mask
config_type_kernel_regularisation =
config_type_sigma =
kernel_regularisation_is_per_atom = T
sigma_per_atom = T
do_copy_atoms_file = T
do_copy_at_file = F
sparse_separate_file = T
sparse_use_actual_gpcov = F
gap_file = gap_new.xml
gp_file = GAP.xml
verbosity = NORMAL
rnd_seed = -1
openmp_chunk_size = 1
do_ip_timing = F
template_file = template.xyz
sparsify_only_no_fit = F

========================================  ======================================


============== Gaussian Approximation Potentials - Database fitting ============


Initial parsing of command line arguments finished.
Found 1 GAPs.
Descriptors have been parsed
XYZ file read
Old GAP: {distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}
New GAP: {distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=8 Z2=8}
New GAP: {distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=8 Z2=1}
New GAP: {distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=1 Z2=1}
Multispecies support added where requested

===================== Report on number of descriptors found ====================

---------------------------------------------------------------------
Descriptor: distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=8 Z2=8
Number of descriptors:                        12634
Number of partial derivatives of descriptors: 75804
---------------------------------------------------------------------
Descriptor: distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=8 Z2=1
Number of descriptors:                        61560
Number of partial derivatives of descriptors: 369360
---------------------------------------------------------------------
Descriptor: distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform               n_sparse=10 Z1=1 Z2=1
Number of descriptors:                        57866
Number of partial derivatives of descriptors: 347196

========================================  ======================================

E0/atom =   0.32100000000000000E+001  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.45999999999999996E+001  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000

========== Report on number of target properties found in training XYZ: ========

Number of target energies (property name: energy) found: 63
Number of target local_properties (property name: local_property) found: 0
Number of target forces (property name: forces) found: 14829
Number of target virials (property name: virial) found: 0
Number of target Hessian eigenvalues (property name: hessian) found: 0

================================= End of report ================================


===== Report on per-configuration/per-atom sigma (error parameter) settings ====

Number of per-configuration setting of energy_sigma found:     0
Number of per-configuration setting of force_sigma found:      0
Number of per-configuration setting of virial_sigma found:     0
Number of per-configuration setting of hessian_sigma found:    0
Number of per-atom setting of force_atom_sigma found:          0
Number of per-component setting of force_component_sigma found:          0

================================= End of report ================================

Cartesian coordinates transformed to descriptors
Started sparse covariance matrix calculation of coordinate 1

Finished sparse covariance matrix calculation of coordinate 1
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1_sparse  done in .55991000000000013E-001 cpu secs, .55721998214721680E-001 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1         done in .55991000000000013E-001 cpu secs, .55772781372070312E-001 wall clock secs.
Started sparse covariance matrix calculation of coordinate 2

Finished sparse covariance matrix calculation of coordinate 2
TIMER: gpFull_covarianceMatrix_sparse_Coordinate2_sparse  done in .27095900000000006 cpu secs, .27118396759033203 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate2         done in .27095900000000006 cpu secs, .27123498916625977 wall clock secs.
Started sparse covariance matrix calculation of coordinate 3

Finished sparse covariance matrix calculation of coordinate 3
TIMER: gpFull_covarianceMatrix_sparse_Coordinate3_sparse  done in .25396199999999991 cpu secs, .25434184074401855 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate3         done in .25396199999999991 cpu secs, .25439310073852539 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_LinearAlgebra       done in .13997999999999955E-001 cpu secs, .13936042785644531E-001 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_FunctionValues      done in .00000000000000000E+000 cpu secs, .46968460083007812E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse                     done in .59790999999999994 cpu secs, .59833621978759766 wall clock secs.
SYSTEM ABORT: Traceback (most recent call last)
File "/u/home/g/gengsun/project/programs/QUIP/QUIP/src/libAtoms/linearalgebra.f95", line 2329 kind
unspecified
LA_Matrix_Factorise: cannot factorise, error: 9
```
And this is the first frame:

```
81
Lattice="9.312844978309194 0.0 0.0 0.0 9.312844978309194 0.0 0.0 0.0 9.312844978309194" Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy=71.71319028943991 pbc="T T T"
O        0.00000000       0.00000000       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       0.76323900       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       8.54960598       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       0.00000000       3.22354366      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       0.76323900       2.62723466       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       8.54960598       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       0.00000000       6.32782532      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       0.76323900       5.73151632       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       8.54960598       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       3.10428166       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        0.00000000       3.86752066       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       2.34104266       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       3.10428166       3.22354366      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        0.00000000       3.86752066       2.62723466       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       3.10428166       6.32782532      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        0.00000000       3.86752066       5.73151632       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       2.34104266       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       6.20856332       0.11926200      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        0.00000000       6.97180232       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       5.44532432       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       6.20856332       3.22354366      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        0.00000000       6.97180232       2.62723466       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       5.44532432       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        0.00000000       6.20856332       6.32782532      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        0.00000000       6.97180232       5.73151632       0.00000000       5.21893682      -4.05591796       1.35042099
H        0.00000000       5.44532432       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       0.00000000       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        3.10428166       0.76323900       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       8.54960598       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       0.00000000       3.22354366      -0.00000000       0.00000000       8.11183591      -0.04479790
H        3.10428166       0.76323900       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       8.54960598       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       0.00000000       6.32782532      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        3.10428166       0.76323900       5.73151632      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       8.54960598       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       3.10428166       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        3.10428166       3.86752066       8.83579798      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       2.34104266       8.83579798      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       3.10428166       3.22354366      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        3.10428166       3.86752066       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       3.10428166       6.32782532      -0.00000000      -0.00000000       8.11183591      -0.04479790
H        3.10428166       3.86752066       5.73151632       0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       2.34104266       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       6.20856332       0.11926200      -0.00000000       0.00000000       8.11183591      -0.04479790
H        3.10428166       6.97180232       8.83579798       0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       5.44532432       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       6.20856332       3.22354366       0.00000000      -0.00000000       8.11183591      -0.04479790
H        3.10428166       6.97180232       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       5.44532432       2.62723466      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        3.10428166       6.20856332       6.32782532       0.00000000      -0.00000000       8.11183591      -0.04479790
H        3.10428166       6.97180232       5.73151632      -0.00000000       5.21893682      -4.05591796       1.35042099
H        3.10428166       5.44532432       5.73151632       0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       0.00000000       0.11926200       0.00000000       0.00000000       8.11183591      -0.04479790
H        6.20856332       0.76323900       8.83579798      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       8.54960598       8.83579798      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       0.00000000       3.22354366       0.00000000       0.00000000       8.11183591      -0.04479790
H        6.20856332       0.76323900       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       8.54960598       2.62723466      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       0.00000000       6.32782532       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       0.76323900       5.73151632      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       8.54960598       5.73151632      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       3.10428166       0.11926200       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       3.86752066       8.83579798      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       2.34104266       8.83579798       0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       3.10428166       3.22354366       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       3.86752066       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       3.10428166       6.32782532       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       3.86752066       5.73151632      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       2.34104266       5.73151632      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       6.20856332       0.11926200       0.00000000       0.00000000       8.11183591      -0.04479790
H        6.20856332       6.97180232       8.83579798      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       5.44532432       8.83579798      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       6.20856332       3.22354366       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       6.97180232       2.62723466      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       5.44532432       2.62723466      -0.00000000      -5.21893682      -4.05591796       1.35042099
O        6.20856332       6.20856332       6.32782532       0.00000000      -0.00000000       8.11183591      -0.04479790
H        6.20856332       6.97180232       5.73151632      -0.00000000       5.21893682      -4.05591796       1.35042099
H        6.20856332       5.44532432       5.73151632      -0.00000000      -5.21893682      -4.05591796       1.35042099
```

**Comment by gabor1** [comment]
so I ran your command line on the configuration you sent me, and it ran fine. So I’m guessing that something might be wrong with your datafile. Can you please do a binary search by chopping your datafile in half, testing on both halves etc. until you find which frame is giving you the error. then we can get to the bottom of it. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by GengSS** [comment]
Dear Prof. Csányi,
Thanks for your suggestion,
I tried to use only one frame as I sent to you, but it is strange that I still have the same error.
and I also tried a few other frames, the error persists regardless of the input "train.xyz"

Best,
Geng

**Comment by gabor1** [comment]
Which lapack library are you using? Can you switch to a different one?

-- Gábor

**Comment by GengSS** [comment]
Dear Prof. Csányi,
I have tried openblas, and then switched to blas/lapack from netlib.
Both of them result in the same error above.

Best,
Geng

**Comment by gabor1** [comment]
Weird. Can you please try to do it inside our docker: 

https://hub.docker.com/r/libatomsquip/quip/

That’s where I tried your exact command line, and as I wrote, it worked fine with your data frame. Doing it in the docker will again eliminate some possibilities. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by GengSS** [comment]
Dear Prof. Csányi,
Thanks for the suggestion.
I have little experience with using Docker.
I am working on an HPC cluster, and I will contact the admin for some help to set it up.

Best,

Geng

**Comment by gabor1** [comment]
Geng, I am not recommending using Docker on the HPC. Can you test this on your desktop computer, both using docker and without ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by GengSS** [comment]
Dear Prof. Csányi,
I see. I will install the QUIP and GAP on the local desktop and figure out how it works.
I will get back to you soon. Thanks.
Best,
Geng

**Comment by GengSS** [comment]
A quick update,
Indeed, when I compile QUIP and GAP on my local desktop, the program runs fine without error.

Best,
Geng

**Comment by gabor1** [comment]
ok. I think you are in a position to take it forward from here, because the problem is lapack on your HPC...

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by GengSS** [comment]
Dear Prof. Csányi,
Thank you very much for your help.
I will dig into the compiling process and find out what could be the error on HPC.

Best Regards,
Geng
