### ISSUE TITLE
A warning during training the GAP model: 

### ISSUE THREAD

**Issue by FuzhuLiu** [libAtoms/QUIP#239]
Dear developers:
I am trying to training a GAP model, I follow the turorial about the water poterntial: https://libatoms.github.io/GAP/gap_fitting_tutorial.html. 
However, when I move to my data, there have some warnings:
.........
===== Report on per-configuration/per-atom sigma (error parameter) settings ====

Number of per-configuration setting of energy_sigma found:     0
Number of per-configuration setting of force_sigma found:      0
Number of per-configuration setting of virial_sigma found:     0
Number of per-configuration setting of hessian_sigma found:    0
Number of per-atom setting of force_atom_sigma found:          0
Number of per-component setting of force_component_sigma found:          0

================================= End of report ================================

WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=79 Z2=79
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=79 Z2=46
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=79 Z2=8
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=79 Z2=6
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=46 Z2=46
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=46 Z2=8
WARNING: gpCoordinates_sparsify: number of data points (1) less than the number of sparse points (10), number of sparse points changed to 1
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=1 Z2=1
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=1 Z2=8
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=1 Z2=6
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=8 Z2=8
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (10), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=2.0 covariance_type=ard_se delta=0.5 theta_uniform=1 sparse_method=uniform               n_sparse=10 Z1=6 Z2=6
Cartesian coordinates transformed to descriptors
Started sparse covariance matrix calculation of coordinate 1

Finished sparse covariance matrix calculation of coordinate 1
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1_sparse  done in .64000000000064006E-004 cpu secs, .63570998463546857E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1         done in .18689999999992324E-002 cpu secs, .18691469995246734E-002 wall clock secs.
Started sparse covariance matrix calculation of coordinate 2
........

The WARNING would result in the error during predicting the energy and forces on train.xyz and validate.xyz:
SYSTEM ABORT: Traceback (most recent call last)
File "/home/fuzhu/QUIP/src/libAtoms/linearalgebra.f95", line 2309 kind unspecified
LA_Matrix_Factorise: cannot factorise, error: -4            
SYSTEM ABORT: Traceback (most recent call last)
File "/home/fuzhu/QUIP/src/libAtoms/linearalgebra.f95", line 2309 kind unspecified
LA_Matrix_Factorise: cannot factorise, error: -4 
   
It looks the <number of data points> should not be the 0, 
did you enperience the errors and how to figure it out?

Best,
Fuzhu Liu

**Comment by gabor1** [comment]
Attach a small sample of your data file and the full training command line

-- Gábor
