### ISSUE TITLE
'quippy' has no attribute 'descriptors_module'

### ISSUE THREAD

**Issue by Dong-Shiyu** [libAtoms/QUIP#321]
I have installed the quip and quippy ,but when I am following the tutorial at Computing descriptors from python 
[https://libatoms.github.io/GAP/quippy-descriptor-tutorial.html](url)
```>>>desc = descriptors.Descriptor("distance_2b Z1=6 Z2=6 cutoff=4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sydong/anaconda3/lib/python3.8/site-packages/quippy/descriptors.py", line 73, in __init__
    self._quip_descriptor = quippy.descriptors_module.descriptor(args_str)
AttributeError: module 'quippy' has no attribute 'descriptors_module'
```

and the dictionary at /home/sydong/anaconda3/lib/python3.8/site-packages/quippy/descriptors.py
```[sydong@lw03 QUIP]$ ls /home/sydong/anaconda3/lib/python3.8/site-packages/quippy
atoms_module.py        convert.py            dynamicalsystem_module.py  nye_tensor_module.py  potential.py                quip
atoms_types_module.py  descriptors.py        dynamicalsystem.py         nye_tensor.py         potential_simple_module.py  _quippy.cpython-38-x86_64-linux-gnu.so
cli.py                 dictionary_module.py  __init__.py                potential_module.py   __pycache__                 system_module.py
```
do not have a 'descriptors_module' 
what should I do?

**Comment by jameskermode** [comment]
you most likely forgot to set `HAVE_GAP=1` when you ran `make config`. You can edit this setting in the `build.${QUIP_ARCH}/Makefile.inc`, then `make deepclean` and rebuild.

**Comment by Dong-Shiyu** [comment]
Thank for your instruction.It works

**Comment by jameskermode** [comment]
great - I'll close the issue.
