### ISSUE TITLE
LA_Matrix_Factorise error

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/QUIP#575]
Hello! 
I'm trying to learn using workflow package and implementing my system to workflow package. 
But I've encountered following error saying LA matrix factorization has failed. 
I've already seen [previous post](https://github.com/libAtoms/QUIP/issues/229)  discussing this issue, but didn't help really to solve this problem. 
I've tried running this both in my laptop and HPC and have failed in either systems.
Also changed difference version of MKL version but didn't really help solving the issue. 
Please find attached my execution files (python files and training.xyz etc) 
Could someone advice on why this happens and how can be circumvented?
Many thanks in advance!

Best 
Hyunwook 

```
SYSTEM ABORT: Traceback (most recent call last)
File "/io/QUIP/src/libAtoms/linearalgebra.f95", line 2329 kind unspecified
LA_Matrix_Factorise: cannot factorise, error: 12            
Note: The following floating-point exceptions are signalling: IEEE_OVERFLOW_FLAG
STOP 1
Traceback (most recent call last):
  File "/raven/u/hjung/Softwares/workflow/examples/test/batch_gap_fit.py", line 422, in <module>
    main(verbose=True)
  File "/raven/u/hjung/Softwares/workflow/examples/test/batch_gap_fit.py", line 336, in main
    get_gap(training, gap_name, Zs, length_scales, gap_params, run_dir=GAP_dir)
  File "/raven/u/hjung/Softwares/workflow/examples/test/batch_gap_fit.py", line 278, in get_gap
    gap_fit(in_config, gap_name, gap_params,
  File "/raven/u/hjung/Softwares/workflow/wfl/fit/gap/multistage.py", line 441, in fit
    run_gap_fit(database_ci, gap_simple_fit, stdout_file=
stdout_file, verbose=verbose,
  File "/raven/u/hjung/Softwares/workflow/wfl/fit/gap/simple.py", line 177, in run_gap_fit
    assert Path(gap_file).exists()
AssertionError
```

[issue.zip](https://github.com/libAtoms/QUIP/files/11321338/issue.zip)

**Comment by jungsdao** [comment]
It turned out that I was using wrong energy for single atom and other training set. (different xcfunctional and code)
When I synchronized the training set. it works fine.
