### ISSUE TITLE
quippy library reference

### ISSUE THREAD

**Issue by EricPgh** [libAtoms/QUIP#589]
I've compiled and tested the quip and gap_fit binaries. I've run make, make libquip, make quippy, make install-quippy. I did this first without GAP support and didn't find this problem (I ran several functions in jupyter with the built quippy). Now when I've rebuilt (following a make distclean) with HAVE_GAP the cpython .so references a number of descriptor module tokens that I can't seem to find in source code or libraries. The error that comes from doing an import quippy within the conda environment is:

(jp_kernel) [user@sawtooth3 ~]$ python -m quippy
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/user/QUIP-public/build/linux_x86_64_gfortran/quippy/\_\_init\_\_.py", line 2, in <module>
    import quippy._quippy
ImportError: /home/user/QUIP-public/build/linux_x86_64_gfortran/quippy/_quippy.cpython-311-x86_64-linux-gnu.so: undefined symbol: __descriptors_module_MOD_co_angle_3b_calc

**Comment by jameskermode** [comment]
Looks like quippy was somehow compiled without GAP support (HAVE_GAP=0), despite the make distclean which I agree I would have expected to resolve this. 

Is there a reason the binary wheels don’t work for you? You might need to update pip itself before trying to install them.

**Comment by EricPgh** [comment]
pip --version shows 3.11, the OS is CentOS7. The response when I call pip install quippy-ase is that no wheels match the platform.
I now see the module interfaces in descriptors.f95 at least, so it looks like the .so isn't being statically linked to descriptors.o.

**Comment by jameskermode** [comment]
That pip is extremely old, you need to update it to use binary wheels. Can do this in user space with pip install -U pip

**Comment by jameskermode** [comment]
Although more likely 3.11 is the version of Python, not pip. I think we may not have released binary wheels for Python 3.11 yet.

**Comment by EricPgh** [comment]
Sorry, I read it too quick, 23.1.2

**Comment by EricPgh** [comment]
The quippy makefile doesn't appear to include the src/GAP/*.o files containing necessary tokens. It builds and installs when these are included in the linking. This can probably be closed now unless you want to do something else with the issue.

**Comment by jameskermode** [comment]
These objects are included in `libquip_nostub.a` here when `HAVE_GAP=1` is set.
https://github.com/libAtoms/QUIP/blob/public/Makefile#L216

This is linked when producing the `_quippy.so` shared library:
https://github.com/libAtoms/QUIP/blob/public/quippy/Makefile#L119

It could be that this is not cleaned up correctly by `make distclean` so you could try manually removing and rebuilding `libquip_nostub.a`.
