### ISSUE TITLE
error when creating a Dynamics object from an atoms object that has masses

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#6]
Traceback (most recent call last):
  File "run-model-test.py", line 42, in <module>
    import test  # import and run the current test
  File "../tests/liquid/test.py", line 58, in <module>
    dyn_equil = quippy.Dynamics(bulk, 1.0*ase.units.fs, trajectory=None)
  File "/usr/local/quip/2015-06-03/mkl/lib64/python/quippy/dynamicalsystem.py", line 159, in **init**
    if abs(self.atoms.mass/MASSCONVERT - self.atoms.get_masses()) > 1e-3:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by jameskermode** [comment]
Should be fixed in commit 06d46a9c68daa905cea825fc85406cce968533db to public branch

**Comment by jameskermode** [comment]
Closing as now resolved.
