### ISSUE TITLE
undefined symbol: dgemm_

### ISSUE THREAD

**Issue by yg2831** [libAtoms/QUIP#609]
I've got the error code during "make test"
ImportError: /home/kyg/.local/lib/python3.10/site-packages/quippy/_quippy.cpython-310-x86_64-linux-gnu.so: undefined symbol: dgemm_

I searched and figured out my MATH_LINKOPTS can be a key to solve this problem, but I don't know how to fix it
my setting is like this
MATH_LINKOPTS= -llapack.so -lblas.so -L/usr/lib/x86_64-linux-gnu/libblas.so -L/usr/lib/x86_64-linux-gnu/liblapack.so
I tried
-llapck -lblas
-llapack.so -lblas.so

and I appended "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu" at my .bashrc

Plz help me

**Comment by bernstei** [comment]
Th "-L" options should only include the _directory_ that the libraries are in.  The "-l" (lower case ell) options should include the library name _without_ the leading "lib" or the trailing ".a" or ".so" or anything else, so definitely "-llapack -lblas", assuming that's what those libraries are actually named on your system.

**Comment by jameskermode** [comment]
Also often the `-L/directory` option needs to come BEFORE the `-llibrary` options.

**Comment by yg2831** [comment]
MATH_LINKOPTS= -L/usr/lib/x86_64-linux-gnu -llapack -lblas

this is my final result.
-L option comes before -llbrary option and -L includes only directory, -l includes only library name.
but it doesn't work yet :(

it's my .bashrc info
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu

and I checked nm
$ nm -D /usr/lib/x86_64-linux-gnu/liblapack.so | grep 'dgemm_'
                 U dgemm_
$ nm -D /usr/lib/x86_64-linux-gnu/libblas.so | grep 'dgemm_'
000000000004f360 T dgemm_

what can I do another trier ?
I appreciate for your help

**Comment by bernstei** [comment]
First, make sure that you cleaned up and recompiled after you changed those options. Can you upload the full output of the compilation and python install?

Also, what's the output of `ldd /home/kyg/.local/lib/python3.10/site-packages/quippy/quippy.cpython-310-x86_64-linux-gnu.so` ?

**Comment by yg2831** [comment]
Sorry for my late answer.
About the ldd ~~
there's no quippy.cpython~~ but is _quippy.cpython~~

and here's my compile log 

--------------------------------------------------------


kyg@kyg-H510:~/QUIP$ make test
Using QUIP_ARCH=linux_x86_64_gfortran, MODULES=libAtoms Potentials Utils, QUIP_ROOT=/home/kyg/QUIP
********************************************

 Making libAtoms 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/libAtoms/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/libAtoms -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making Potentials 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/Potentials/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/Potentials -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making Utils 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/Utils/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/Utils -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
LIBQUIP_OBJS="ts_params.o transition_state.o elasticity.o phonons.o restraints_constraints_xml.o crackparams.o cracktools.o real_space_covariance.o structure_analysis_traj_routines.o RS_SparseMatrix.o QUIP_Common.o Functions.o Ewald.o Multipole_Interactions.o Partridge_Schwenke_Dipole.o IPEwald.o Yukawa.o Multipoles.o IPModel_GAP.o IPModel_LJ.o IPModel_Morse.o IPModel_FC.o IPModel_SW.o IPModel_Tersoff.o IPModel_EAM_Ercolessi_Adams.o IPModel_Brenner.o IPModel_FS.o IPModel_BOP.o IPModel_FB.o IPModel_Si_MEAM.o IPModel_Brenner_Screened.o IPModel_Brenner_2002.o IPModel_TS.o IPModel_Glue.o IPModel_PartridgeSchwenke.o IPModel_Einstein.o IPModel_Coulomb.o IPModel_Sutton_Chen.o IPModel_FX.o IPModel_HFdimer.o IPModel_BornMayer.o IPModel_Custom.o IPModel_ConfiningMonomer.o IPModel_SW_VP.o IPModel_WaterDimer_Gillan.o IPModel_WaterTrimer_Gillan.o IPModel_Tether.o IPModel_LMTO_TBE.o IPModel_Multipoles.o IPModel_FC4.o IPModel_Spring.o IPModel_DispTS.o IPModel_SCME.o IPModel_MTP.o IPModel_MBD.o IPModel_ZBL.o IPModel_LinearSOAP.o IPModel_TTM_nF.o IPModel_CH4.o IPModel_vdW.o IPModel_RS.o IPModel_Template.o IP.o FilePot.o CallbackPot.o SocketPot.o Potential_simple.o AdjustablePotential.o Potential.o ElectrostaticEmbed.o quip_unified_wrapper.o quip_lammps_wrapper.o Potential_Precon_Minim.o lbfgs.o error.o kind_module.o System.o LinkedList.o ExtendableStr.o MPI_context.o Units.o linearalgebra.o Quaternions.o statistics.o Dictionary.o Table.o ParamReader.o PeriodicTable.o minimization.o Atoms_types.o Connection.o DomainDecomposition.o Atoms.o RigidBody.o Group.o angular_functions.o steinhardt_nelson_qw.o gamma_functions.o Constraints.o Thermostat.o Barostat.o DynamicalSystem.o Spline.o Sparse.o CInOutput.o clusters.o Structures.o frametools.o nye_tensor.o Topology.o Atoms_ll.o ringstat.o histogram1d.o find_surface_atoms.o k_means_clustering.o SocketTools.o partition.o libAtoms.o libAtoms_misc_utils.o libAtoms_utils_no_module.o f90wrap_stub.o ScaLAPACK.o Matrix.o task_manager.o md5.o cutil.o netcdf.o xyz.o sockets.o m_sax_types.o m_sax_tokenizer.o m_sax_reader.o m_sax_parser.o m_sax_operate.o m_sax_xml_source.o FoX_sax.o m_wxml_escape.o m_wxml_core.o m_wxml_overloads.o FoX_wxml.o FoX_utils.o fox_m_utils_mtprng.o fox_m_utils_uuid.o fox_m_utils_uri.o m_common_attrs.o m_common_buffer.o m_common_charset.o m_common_namespaces.o m_common_error.o m_common_elstack.o m_common_io.o FoX_common.o m_common_namecheck.o m_common_entities.o m_common_notations.o m_common_element.o m_common_struct.o m_common_entity_expand.o m_common_content_model.o fox_m_fsys_abort_flush.o fox_m_fsys_array_str.o fox_m_fsys_format.o fox_m_fsys_parse_input.o fox_m_fsys_count_parse_input.o fox_m_fsys_string.o fox_m_fsys_string_list.o fox_m_fsys_realtypes.o fox_m_fsys_varstr.o" && \
	     cd /home/kyg/QUIP/build/linux_x86_64_gfortran && for i in /home/kyg/QUIP/src/fox/objs.linux_x86_64_gfortran/lib/libFoX_sax.a /home/kyg/QUIP/src/fox/objs.linux_x86_64_gfortran/lib/libFoX_wxml.a /home/kyg/QUIP/src/fox/objs.linux_x86_64_gfortran/lib/libFoX_utils.a /home/kyg/QUIP/src/fox/objs.linux_x86_64_gfortran/lib/libFoX_common.a /home/kyg/QUIP/src/fox/objs.linux_x86_64_gfortran/lib/libFoX_fsys.a; do ar -x $i; done && ar -rcs libquip.a $LIBQUIP_OBJS
cd /home/kyg/QUIP/build/linux_x86_64_gfortran && cp libquip.a libquip_nostub.a && ar d libquip_nostub.a f90wrap_stub.o
********************************************

 Making Programs 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/Programs/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/Programs -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making FilePot_drivers 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/FilePot_drivers/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/FilePot_drivers -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making Structure_processors 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/src/Structure_processors/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP VPATH=/home/kyg/QUIP/src/Structure_processors -I/home/kyg/QUIP -I/home/kyg/QUIP/arch
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making quippy 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/quippy/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP -I/home/kyg/QUIP -I/home/kyg/QUIP/arch build
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
/usr/bin/pip install  "f90wrap>=0.2.6"
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: f90wrap>=0.2.6 in /home/kyg/.local/lib/python3.10/site-packages (0.2.13)
Requirement already satisfied: numpy>=1.13 in /home/kyg/.local/lib/python3.10/site-packages (from f90wrap>=0.2.6) (1.25.1)
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
/home/kyg/QUIP/bin/gitversion --hash-only > VERSION
cp -r ../../quippy/quippy/*.py quippy
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Installing quippy 

********************************************
rm -f /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/kyg/QUIP/quippy/Makefile /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/kyg/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/kyg/QUIP -I/home/kyg/QUIP -I/home/kyg/QUIP/arch install
make[1]: Entering directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
make[1]: -c: No such file or directory
/usr/bin/pip install  "f90wrap>=0.2.6"
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: f90wrap>=0.2.6 in /home/kyg/.local/lib/python3.10/site-packages (0.2.13)
Requirement already satisfied: numpy>=1.13 in /home/kyg/.local/lib/python3.10/site-packages (from f90wrap>=0.2.6) (1.25.1)
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
/home/kyg/QUIP/bin/gitversion --hash-only > VERSION
cp -r ../../quippy/quippy/*.py quippy
cp ../../README.md ../../quippy/setup.py .
cp quip md vasp_driver quippy/
/usr/bin/pip install  .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/kyg/QUIP/build/linux_x86_64_gfortran
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ase>=3.17.0 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (3.22.1)
Requirement already satisfied: f90wrap>=0.2.6 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (0.2.13)
Requirement already satisfied: numpy>=1.13 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (1.25.1)
Requirement already satisfied: matplotlib>=3.1.0 in /home/kyg/.local/lib/python3.10/site-packages (from ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (3.7.2)
Requirement already satisfied: scipy>=1.1.0 in /home/kyg/.local/lib/python3.10/site-packages (from ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (1.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (9.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase==0.9+git0.9.14.2.gb0e43ebef.dirty) (2.8.1)
Building wheels for collected packages: quippy-ase
  Building wheel for quippy-ase (setup.py) ... done
  Created wheel for quippy-ase: filename=quippy_ase-0.9+git0.9.14.2.gb0e43ebef.dirty-cp310-cp310-linux_x86_64.whl size=8253738 sha256=99c27fca9063f6826ff11c95c3605946c1e67f67fc7353ba1a437897c6220d9a
  Stored in directory: /tmp/pip-ephem-wheel-cache-luehe47z/wheels/d6/db/9a/35209a9dbf39967be8ab5c6e076d7f2daca271950fc0c586d8
Successfully built quippy-ase
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: quippy-ase
  Attempting uninstall: quippy-ase
    Found existing installation: quippy-ase 0.9+git0.9.14.2.gb0e43ebef.dirty
    Uninstalling quippy-ase-0.9+git0.9.14.2.gb0e43ebef.dirty:
      Successfully uninstalled quippy-ase-0.9+git0.9.14.2.gb0e43ebef.dirty
  WARNING: The scripts md, quip, quip-config and vasp_driver are installed in '/home/kyg/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed quippy-ase-0.9+git0.9.14.2.gb0e43ebef.dirty
make[1]: Leaving directory '/home/kyg/QUIP/build/linux_x86_64_gfortran'
rm /home/kyg/QUIP/build/linux_x86_64_gfortran/Makefile
make -C tests -I/home/kyg/QUIP -I/home/kyg/QUIP/arch -I/home/kyg/QUIP/build/linux_x86_64_gfortran
make[1]: Entering directory '/home/kyg/QUIP/tests'
HAVE_GAP=0 HAVE_SCALAPACK=0 QUIP_ARCH=linux_x86_64_gfortran python3 run_all.py -v
/home/kyg/QUIP/tests/run_all.py:22: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import get_platform
/home/kyg/QUIP/tests/run_all.py:23: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_python_version
Traceback (most recent call last):
  File "/home/kyg/QUIP/tests/run_all.py", line 25, in <module>
    import quippy
  File "/home/kyg/.local/lib/python3.10/site-packages/quippy/__init__.py", line 2, in <module>
    import quippy._quippy
ImportError: /home/kyg/.local/lib/python3.10/site-packages/quippy/_quippy.cpython-310-x86_64-linux-gnu.so: undefined symbol: dgemm_
make[1]: *** [Makefile:31: all] Error 1
make[1]: Leaving directory '/home/kyg/QUIP/tests'
make: *** [Makefile:296: test] Error 2

**Comment by bernstei** [comment]
> there's no quippy.cpython~~ but is _quippy.cpython~~

Umm - this line
> ImportError: /home/kyg/.local/lib/python3.10/site-packages/quippy/quippy.cpython-310-x86_64-linux-gnu.so: undefined symbol: dgemm

lists a file.  Does that file actually not exist?

**Comment by yg2831** [comment]
kyg@kyg-H510:~/.local/lib/python3.10/site-packages/quippy$ ls
atoms_module.py        dynamicalsystem_module.py  nye_tensor.py               _quippy.cpython-310-x86_64
atoms_types_module.py  dynamicalsystem.py         potential_module.py         _quippy.cpython-310-x86_64-linux-gnu.so
cli.py                 gap_tools.py               potential.py                system_module.py
convert.py             __init__.py                potential_simple_module.py  test.py
descriptors.py         md                         __pycache__                 vasp_driver
dictionary_module.py   nye_tensor_module.py       quip

I changed _quippy.cpython-310-x86_64-linux-gnu.so > quippy.cpython-310-x86_64-linux-gnu.so
by ImportError: /home/kyg/.local/lib/python3.10/site-packages/quippy/quippy.cpython-310-x86_64-linux-gnu.so: undefined symbol: dgemm           but during "make test" process "make install" get start so another _quippy.cpython-310-x86_64-linux-gnu.so is produced and error is same :(

**Comment by bernstei** [comment]
First, please use code blocks (three back quotes) when pasting command output, otherwise the spacing gets messed up.  

Second, don't blindly rename files in automatically installed directories - that's essentially _never_ a good idea. 

I'm not sure why the filename has an extra underscore, but please paste the output of `ldd` on the file with the closest name, e.g.
```
ldd /home/kyg/.local/lib/python3.10/site-packages/quippy/*.so
```

**Comment by yg2831** [comment]
Thx for ur advice.

`ldd /home/kyg/.local/lib/python3.10/site-packages/quippy/*.so`
output ->
	`linux-vdso.so.1 (0x00007ffca19ba000)`
	`libgfortran.so.5 => /usr/lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f0cfaa00000)`
	`libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f0cfad19000)`
	`libmvec.so.1 => /usr/lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f0cfa903000)`
	`libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d0110a000)`
	`libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f0cfa600000)`
	`libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f0d010c0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0d0112c000)`

**Comment by bernstei** [comment]
I'm at a loss.  The filename starting with underscore is true on my installation too, so I guess that's normal.  Do you get the error if you do
```
python -c "import quippy"
```
(or `python3` or whatever the right python 3.10 executable is named)

Also, is there a specific reason you're not just using the pip installation?

**Comment by yg2831** [comment]
`kyg@kyg-H510:~$ python3 -c "import quippy"`
`Traceback (most recent call last):`
`  File "<string>", line 1, in <module>`
`  File "/home/kyg/.local/lib/python3.10/site-packages/quippy/__init__.py", line 2, in <module>`
    `import quippy._quippy`
`ImportError: /home/kyg/.local/lib/python3.10/site-packages/quippy/_quippy.cpython-310-x86_64-linux-gnu.so: undefined symbol: dgemm_`

i don't understand I'm not using the pip installation,
Pip installation for what??

**Comment by bernstei** [comment]
> Pip installation for what??

For quip/quippy - `python3 -m pip install quippy-ase`.  I've been assuming, given that your make test is failing during the python part, that what you want is the python interface, although the python installation also includes some of the fortran executables, including `gap_fit`, `quip`, `md`, and maybe a couple others.

**Comment by yg2831** [comment]
u mean, i have to proceed `python3 -m pip install quippy-ase`?

but i think i already got this
`kyg@kyg-H510:~/QUIP/build/linux_x86_64_gfortran$ python3 -m pip install quippy-ase`

`Defaulting to user installation because normal site-packages is not writeable`
`Requirement already satisfied: quippy-ase in /home/kyg/.local/lib/python3.10/site-packages (0.9+git0.9.14.2.gb0e43ebef.dirty)`
`Requirement already satisfied: ase>=3.17.0 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase) (3.22.1)`
`Requirement already satisfied: f90wrap>=0.2.6 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase) (0.2.13)`
`Requirement already satisfied: numpy>=1.13 in /home/kyg/.local/lib/python3.10/site-packages (from quippy-ase) (1.25.1)`
`Requirement already satisfied: matplotlib>=3.1.0 in /home/kyg/.local/lib/python3.10/site-packages (from ase>=3.17.0->quippy-ase) (3.7.2)`
`Requirement already satisfied: scipy>=1.1.0 in /home/kyg/.local/lib/python3.10/site-packages (from ase>=3.17.0->quippy-ase) (1.11.1)`
`Requirement already satisfied: contourpy>=1.0.1 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (1.1.0)`
`Requirement already satisfied: cycler>=0.10 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (0.11.0)`
`Requirement already satisfied: fonttools>=4.22.0 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (4.41.1)`
`Requirement already satisfied: kiwisolver>=1.0.1 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (1.4.4)`
`Requirement already satisfied: packaging>=20.0 in /home/kyg/.local/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (23.1)`
`Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (9.0.1)`
`Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (2.4.7)`
`Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib>=3.1.0->ase>=3.17.0->quippy-ase) (2.8.1)`
`DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063`
