### ISSUE TITLE
QUIPPY installation issue

### ISSUE THREAD

**Issue by bose045** [libAtoms/QUIP#633]
I am trying to install QUIP and QUIPPY using make quippy. My makefile is:

`MATH_LINKOPTS=-llapack -lblas
PYTHON=/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/bin/python
PIP=/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/bin/pip
EXTRA_LINKOPTS=
HAVE_CP2K=0
HAVE_VASP=1
HAVE_TB=0
HAVE_PRECON=1
HAVE_LOTF=1
HAVE_ONIOM=0
HAVE_LOCAL_E_MIX=0
HAVE_QC=0
HAVE_GAP=1
HAVE_DESCRIPTORS_NONCOMMERCIAL=1
HAVE_QR=1
HAVE_SCALAPACK=0
HAVE_THIRDPARTY=0
HAVE_FX=0
HAVE_SCME=0
HAVE_MTP=0
HAVE_MBD=0
HAVE_TTM_NF=0
HAVE_CH4=0
HAVE_NETCDF4=0
HAVE_MDCORE=0
HAVE_ASAP=0
HAVE_CGAL=0
HAVE_METIS=0
HAVE_LMTO_TBE=0
SIZEOF_FORTRAN_T=2`

I am getting following error:

`Traceback (most recent call last):
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/bin/f2py-f90wrap", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/site-packages/f90wrap/scripts/f2py_f90wrap.py", line 214, in main
    numpy.f2py.main()
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 766, in main
    run_compile()
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 738, in run_compile
    builder.compile()
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 176, in compile
    self.sources = _prepare_sources(self.modulename, self.sources, self.build_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 192, in _prepare_sources
    shutil.copy(source, bdir)
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/xxxx/u/home/XXXX/XXXXxxxx/scratch-shared/miniconda3/envs/quip/lib/python3.12/shutil.py", line 240, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'f90wrap_Atoms_types.f90' and './f90wrap_Atoms_types.f90' are the same file
make[1]: *** [Makefile:118: quippy/_quippy.cpython-312-powerpc64le-linux-gnu.so] Error 1
make[1]: Leaving directory '/xxxx/u/scratch/XXXX/XXXXxxxx/git_repos/QUIP/build/linux_ppc64le_gfortran'
make: *** [Makefile:230: quippy] Error 2
`

Any clue why is it trying to copy same files to same path? Any help is appreciated. Thanks.

**Comment by pzeiger** [comment]
I run into the same issue. Have you managed to fix it @bose045?

**Comment by 13314400762** [comment]
I run into the same issue.

**Comment by smiet** [comment]
Running into  a similar issue with a different code and occurred when my runner updated to python 3.12. If you can downgrade to python 3.11, this would probably work (use a pyenv or conda to create a 3.11 environment).

**Comment by albapa** [comment]
We're working on changing the build system to make it work with python 3.12 and beyond.
