### ISSUE TITLE
Tests fail with ase-3.15

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#85]
```
======================================================================
ERROR: test_equal (test_ase.TestConvert_ExtraProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/libAtoms/QUIP/tests/test_ase.py", line 46, in test_equal
    self.assertEqual(self.dia_quippy, self.dia_quippy_2)
  File "/home/travis/build/libAtoms/QUIP/tests/quippytest.py", line 62, in assertEqual
    self.fail('%s != %s' % (a,b))
  File "/home/travis/build/libAtoms/QUIP/quippy/build/linux_x86_64_gfortran/lib.linux-x86_64-2.7/quippy/oo_fortran.py", line 420, in __str__
    v = getattr(self,k)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/ase/atoms.py", line 1772, in adsorbate_info
    return self.info['adsorbate_info']
  File "/home/travis/build/libAtoms/QUIP/quippy/build/linux_x86_64_gfortran/lib.linux-x86_64-2.7/quippy/dictionary.py", line 203, in __getitem__
    raise KeyError('Key "%s" not found ' % k)
KeyError: 'Key "adsorbate_info" not found '
----------------------------------------------------------------------
```

**Comment by tdaff** [comment]
Looks like there have been some renamed properties too:

- `magmoms` -> `initial_magmoms`
- `charges` -> `initial_charges`

**Comment by gabor1** [comment]
ugh

-- Gábor
